kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: latency-benchmark
  namespace: default
rules:
  - apiGroups:
      - "neo4j.io"
    resources:
      - "neo4jdatabases"
    verbs:
      - "list"
      - "get"
      - "patch"
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: latency-benchmark
  namespace: default
imagePullSecrets:
  - name: gcr-json-key
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: latency-benchmark
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: latency-benchmark
subjects:
  - kind: ServiceAccount
    name: latency-benchmark
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: latency-benchmark
spec:
  revisionHistoryLimit: 1
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: latency-benchmark
  template:
    metadata:
      labels:
        app: latency-benchmark
    spec:
      serviceAccountName: latency-benchmark
      imagePullSecrets:
        - name: gcr-json-key
      containers:
        - name: latency-benchmark
          image: _IMAGE_ID
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "100m"
              memory: "100Mi"
          env:
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: ENVIRONMENT
                  name: orchestra-environment
            - name: IS_PRODUCTION_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  key: IS_PRODUCTION_ENVIRONMENT
                  name: orchestra-environment
            - name: ONLY_DATABASES_WITH_CHAOS_ENABLED
              value: "_ONLY_DATABASES_WITH_CHAOS_ENABLED"
